//whole component generated by Deepseek AI
import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { FaArrowUp } from "react-icons/fa";

const ScrollToTop = () => {
  const [isVisible, setIsVisible] = useState(false);

  // Show the button when the user scrolls down 300px
  const toggleVisibility = () => {
    if (window.pageYOffset > 300) {
      setIsVisible(true);
    } else {
      setIsVisible(false);
    }
  };

  // Scroll to the top of the page
  const scrollToTop = () => {
    window.scrollTo({
      top: 0,
      behavior: "smooth",
    });
  };

  useEffect(() => {
    window.addEventListener("scroll", toggleVisibility);
    return () => window.removeEventListener("scroll", toggleVisibility);
  }, []);

  return (
    <AnimatePresence>
      {isVisible && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: 20 }}
          transition={{ duration: 0.3 }}
          onClick={scrollToTop}
          // style={{
          //   position: "fixed",
          //   bottom: "20px",
          //   right: "20px",
          //   cursor: "pointer",
          //   zIndex: 1000,
          //   backgroundColor: "#007bff",
          //   color: "#fff",
          //   borderRadius: "50%",
          //   padding: "10px",
          //   display: "flex",
          //   alignItems: "center",
          //   justifyContent: "center",
          //   width: "40px",
          //   height: "40px",
          //   boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
          // }}
        >
          <FaArrowUp />
        </motion.div>
      )}
    </AnimatePresence>
  );
};

export default ScrollToTop;